# Generated by Django 6.0.1 on 2026-02-19 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('subject', models.CharField(choices=[('math', 'Математика'), ('physics', 'Физика')], max_length=20, verbose_name='Предмет')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В работе'), ('submitted', 'Отправлено на проверку'), ('checked', 'Проверено')], default='assigned', max_length=20, verbose_name='Статус')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн сдачи')),
                ('submitted_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('checked_date', models.DateField(blank=True, null=True, verbose_name='Дата проверки')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('grade', models.CharField(blank=True, choices=[('5', 'Отлично (5)'), ('4', 'Хорошо (4)'), ('3', 'Удовлетворительно (3)'), ('2', 'Неудовлетворительно (2)'), ('z', 'Зачтено')], max_length=5, null=True, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Probnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название пробника')),
                ('subject', models.CharField(choices=[('math', 'Математика'), ('physics', 'Физика')], max_length=20, verbose_name='Предмет')),
                ('month', models.CharField(blank=True, choices=[('', '---------'), ('september', 'Сентябрь'), ('october', 'Октябрь'), ('november', 'Ноябрь'), ('december', 'Декабрь'), ('january', 'Январь'), ('february', 'Февраль'), ('march', 'Март'), ('april', 'Апрель'), ('may', 'Май')], help_text='Выберите месяц для ежемесячной аттестации', max_length=20, null=True, verbose_name='Месяц аттестации')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Дата назначения')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн сдачи')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('checked', 'Проверен')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Баллы')),
                ('max_score', models.IntegerField(default=100, verbose_name='Максимальный балл')),
                ('grade', models.CharField(blank=True, choices=[('5', 'Отлично (5)'), ('4', 'Хорошо (4)'), ('3', 'Удовлетворительно (3)'), ('2', 'Неудовлетворительно (2)')], max_length=5, null=True, verbose_name='Оценка')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пробник',
                'verbose_name_plural': 'Пробники',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework_files/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('teacher', 'Файл преподавателя'), ('student', 'Файл ученика')], default='teacher', max_length=20, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание файла')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='students.homework')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл домашнего задания',
                'verbose_name_plural': 'Файлы домашних заданий',
            },
        ),
        migrations.CreateModel(
            name='ProbnikFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='probnik_files/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('teacher', 'Файл преподавателя'), ('student', 'Файл ученика')], default='teacher', max_length=20, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание файла')),
                ('probnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='students.probnik')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл пробника',
                'verbose_name_plural': 'Файлы пробников',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('class_name', models.CharField(max_length=50, verbose_name='Класс')),
                ('telegram_username', models.CharField(help_text='Начинается с @', max_length=100, verbose_name='Telegram @username')),
                ('parent_telegram', models.CharField(blank=True, help_text='Начинается с @', max_length=100, verbose_name='Telegram родителя')),
                ('parent_name', models.CharField(max_length=200, verbose_name='Имя родителя')),
                ('school', models.CharField(max_length=200, verbose_name='Школа')),
                ('exam_types', models.CharField(blank=True, default='', help_text='Выберите типы подготовки (можно несколько)', max_length=200, verbose_name='Типы подготовки')),
                ('current_level', models.CharField(max_length=100, verbose_name='Текущий уровень')),
                ('weak_topics', models.TextField(verbose_name='Слабые темы')),
                ('start_date', models.DateField(verbose_name='Дата начала занятий')),
                ('exam_date_oge_math', models.DateField(blank=True, null=True, verbose_name='Дата ОГЭ по математике')),
                ('exam_date_oge_physics', models.DateField(blank=True, null=True, verbose_name='Дата ОГЭ по физике')),
                ('exam_date_ege_math', models.DateField(blank=True, null=True, verbose_name='Дата ЕГЭ по математике')),
                ('exam_date_ege_physics', models.DateField(blank=True, null=True, verbose_name='Дата ЕГЭ по физике')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='probnik',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probniks', to='students.student'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='students.student'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('bio', models.TextField(blank=True, verbose_name='О преподавателе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='StudyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название файла')),
                ('subject', models.CharField(choices=[('math', 'Математика'), ('physics', 'Физика'), ('general', 'Общие материалы')], default='general', max_length=20, verbose_name='Предмет')),
                ('file_type', models.CharField(choices=[('theory', 'Теория'), ('practice', 'Практика'), ('demo', 'Демоверсия'), ('template', 'Шаблон'), ('other', 'Другое')], default='theory', max_length=20, verbose_name='Тип файла')),
                ('file', models.FileField(upload_to='study_files/%Y/%m/%d/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_files', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='students.teacher', verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Учебный файл',
                'verbose_name_plural': 'Учебные файлы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='probnik',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_probniks', to='students.teacher', verbose_name='Назначил'),
        ),
        migrations.AddField(
            model_name='homework',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homework', to='students.teacher', verbose_name='Назначил'),
        ),
    ]
