# Generated by Django 6.0.4 on 2026-06-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Числовой ID чата ученика (заполняется автоматически после /start)', null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Числовой ID чата для отправки уведомлений (заполняется автоматически)', null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
