# Generated by Django 6.0.4 on 2026-07-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_telegram_chat_id_teacher_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='google_sheet_url',
            field=models.URLField(blank=True, help_text='Ссылка на Google таблицу с успеваемостью ученика', max_length=500, verbose_name='Ссылка на Google таблицу'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В работе'), ('checked', 'Проверено')], default='assigned', max_length=20, verbose_name='Статус'),
        ),
    ]
