# Generated by Django 6.0.4 on 2026-06-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_telegram_chat_id_teacher_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыто'),
        ),
        migrations.AddField(
            model_name='probnik',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыто'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В работе'), ('checked', 'Проверено')], default='assigned', max_length=20, verbose_name='Статус'),
        ),
    ]
