# Generated by Django 6.0.4 on 2026-07-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_google_sheet_url_alter_homework_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='probnik',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Если включено, пробник не будет отображаться у ученика', verbose_name='Скрыть от ученика'),
        ),
    ]
