# Generated by Django 6.0.4 on 2026-07-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_probnik_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Если включено, задание не будет отображаться у ученика', verbose_name='Скрыть от ученика'),
        ),
    ]
