# Generated by Django 6.0.4 on 2026-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_homework_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probnik',
            name='grade',
        ),
        migrations.AlterField(
            model_name='homework',
            name='grade',
            field=models.CharField(blank=True, choices=[('z', 'Зачтено'), ('nz', 'Не зачтено')], max_length=5, null=True, verbose_name='Оценка'),
        ),
    ]
