# Generated by Django 6.0.4 on 2026-07-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_probnik_grade_alter_homework_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текущий уровень'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя родителя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=200, verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='weak_topics',
            field=models.TextField(blank=True, verbose_name='Слабые темы'),
        ),
    ]
