# Generated by Django 6.0.4 on 2026-07-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Числовой ID чата родителя (заполняется автоматически после /start)', null=True, verbose_name='Telegram Chat ID родителя'),
        ),
    ]
