# Generated by Django 6.0.4 on 2026-08-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_parent_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Числовой ID чата в Telegram', unique=True, verbose_name='Telegram Chat ID')),
                ('username', models.CharField(blank=True, help_text='Username в Telegram (может быть пустым, если скрыт)', max_length=100, verbose_name='Telegram @username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя в Telegram')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия в Telegram')),
                ('is_parent', models.BooleanField(default=False, help_text='True, если этот chat_id принадлежит родителю ученика', verbose_name='Это родитель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата первой записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_users', to='students.student', verbose_name='Связанный ученик')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_users', to='students.teacher', verbose_name='Связанный преподаватель')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
                'ordering': ['-updated_at'],
            },
        ),
    ]
