# Generated by Django 6.0.4 on 2026-08-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_add_telegramuser_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bonus_balance',
            field=models.IntegerField(default=0, help_text='Бонусные рубли, которые ученик получает за проделанную работу', verbose_name='Бонусные рубли'),
        ),
    ]
